pages:
  stage: deploy
  script:
    - mkdir -p public
    - echo "/* https://katyukha.github.io/odoo-helper-scripts/:splat 301" > public/_redirects
  artifacts:
    paths:
      - public
  only:
    - master
